### ISSUE TITLE
[Zadanie] Przykładowe dane do p.1

### ISSUE THREAD

**Issue by wjurkowski** [mkrasinski/CodonProb#3]
1. sekwencje DNA i aminokwasow wybranej grupy 10-20 bialek
2. sekwencje DNA i aminokwasow podgrupy bialek ze znana struktura

**Comment by wjurkowski** [comment]
Wykorzystaj kod (dostepny z innego projektu) wykorzystujacy API do pozyskania tych danych

**Comment by wjurkowski** [comment]
Wrzuc dane do katalogu Dane na GD

**Comment by mpiwowar** [comment]
Ponizej przykładowe identyfikatory białek i mRNA.
NP_\* - identyfikatory białek z bazy RefSeq
NM_\* - identyfikatory mRNA (transkryptów) z bazy RefSeq
XP_\* - oznacza białko przewidziane teoretycznie
Zestawienie NP_\* obok NM_\* oznacza, ze NM_ jest martyca dla NP_ (stanowia komplet danych).
Izoformy to obiekty powstałe z tego samego genu (= z jednego genu czasami, ale nie zawsze 
może powstawać więcej niz jeden produkt białkowy) 

NP_055040.2. NM_014225.5
NP_005624.2. NM_005633.3
NP_037366.1. NM_013234.3
NP_550433.1. NM_080911.2
NP_002677.1. NM_002686.4
NP_001701.2. NM_001710.5
NP_002280.1. NM_002289.2
NP_004036.1. NM_004045.3

Cztery izoformy tego samego genu:
NP_001002009.1. NM_001002009.2
NP_001002010.1. NM_001002010.2
NP_001159590.1. NM_001166118.2
NP_057573.2. NM_016489.12

Dwie izoformy tego samego genu:
NP_115564.2. NM_032188.2
NP_892003.2. NM_182958.2

pięć izoform tego samego genu:
NP_001107593.1. NM_001114121.2
NP_001107594.1. NM_001114122.2
NP_001231775.1. NM_001244846.1
NP_001265.2. NM_001274.5
XP_006718822.1. XM_006718759.1
