### ISSUE TITLE
[Problem] Brak dostepu

### ISSUE THREAD

**Issue by wjurkowski** [mkrasinski/CodonProb#4]
Wyglada na to ze ze nie mam praw zapisu do CodonProb

Prosze dodac nas jako wspolpracwonikow w tym repozytorium - w tej chwili nie moge np. przypisywac watkow do okreslonych osob

**Comment by mkrasinski** [comment]
Zrobione. Dodałem Państwa jako "collaboratorow", powinno to pozwolić na pełny dostęp do wszystkich narzędzi w repozytorium. Proszę o potwierdzenie czy już jest ok.

**Comment by wjurkowski** [comment]
Wszystko gra!

**Comment by wjurkowski** [comment]
Jeszcze tylko prawa zapisu w CodonProb na G drivie.

**Comment by mkrasinski** [comment]
Prawa zapisu powinny być ok (zle teraz nic nie zmieniałem)... z moich ustawień wynika to co na poniższym screenie.

-screen usuniety-

Bład pojawia się przy edycji czy przy dodawaniu nowego pliku ?

**Comment by wjurkowski** [comment]
Przy dodawaniu katalogu wewnatrz CodonProb. Mysle ze problemem jest
upublicznienie - prosze je usunac.

W dniu 15 kwietnia 2015 15:30 użytkownik mkrasinski <
notifications@github.com> napisał:

**Comment by mkrasinski** [comment]
Usuniete. Prosze dac znac czy to pomoglo.

**Comment by wjurkowski** [comment]
Teraz stracilem dostep. juz rozumiem, nie mam skojarzonego adresu tgac z googlem. Czy moze Pan zszerowac uzywajac -adres usuniety- i -adres usuniety-

**Comment by mkrasinski** [comment]
Zrobione, dodałem te dwa adresy. Teraz juz musi dzialac :)

**Comment by wjurkowski** [comment]
Działa!
