### ISSUE TITLE
[Zadanie] Wykorzystuj kod z innego projektu 

### ISSUE THREAD

**Issue by wjurkowski** [mkrasinski/CodonProb#5]
wykorzystujacy API do pozyskania danych na temat cech sekwencji w okreslonych rejoinach np. definicje egzonow

**Comment by mkrasinski** [comment]
Dodalem skrypt get_region_feature.py ktory wyswietla wybrane cechy, tak jak jest to opisane w tym zasobie : http://rest.ensembl.org/documentation/info/overlap_region 
Przyjalem konwencje w ktorej klent jest zaimplementowany w module ensembl.py, a poszczegolne skrypty obsluguja tylko pobranie danych i ich wyswietlenie (ew w przyszlosci przekazanie dalej lub zapisanie).
Opisalem to w dwoch slowach tutaj : 
https://drive.google.com/open?id=0B8fcuduCFQUNZ2JDT3ZDZlBFZ3M&authuser=0
