### ISSUE TITLE
[Zadanie] VR: dodaj publikacje do Mendeley i kod do repozytorium

### ISSUE THREAD

**Issue by wjurkowski** [mkrasinski/CodonProb#6]

**Comment by mpiwowar** [comment]
???
http://ztis5.if.uj.edu.pl/ZTI/pracownicy/pracownicy.html

-- 
dr Monika Piwowar
Uniwersytet Jagiellonski, Collegium Medicum, ZBiT
mpiwowar@cm-uj.krakow.pl
+48(12)422 77 64; tel. kom. 517197472

**Comment by wjurkowski** [comment]
publikacja dodana

**Comment by wjurkowski** [comment]
kod znajduje sie w https://github.com/wjurkowski/protein-alchemy. Wymaga pewnej dyskusji - zajmijmy sie tym pozniej po zakonczeniu aktualnej czesci
