### ISSUE TITLE
[Zadanie] Analiza rozkladu kodonow: literatura

### ISSUE THREAD

**Issue by mkrasinski** [mkrasinski/CodonProb#7]
Prosze o dodanie publikacji ktore pomoga mi w pisaniu merytorycznej (nie-technicznej) czesci punktu "1. Analiza rozkładu kodonów w białkach". (http://www.tiem.utk.edu/~gross/bioed/webmodules/aminoacid.htm)
(W Mendeley'u utworzylem grupe "Hiper-zmienne obszary..." i wyslalem zaproszenia)
Prosilbym rowniez o elektroniczna wersje pracy magisterskiej na ktora patrzylismy podczas ostaniego spotkania.

**Comment by wjurkowski** [comment]
Jestesmy juz polaczeni w Mendeley - prosze wyslac zaproszenie do grupy

**Comment by mkrasinski** [comment]
Wyslalem zaproszenia z zakladki "Members", tylko nie wiem czy uzylem wlasciwych adresow email. Czy powinienem je wyslac na adresy gmailowe ?
-screenshot usuniety-

**Comment by mpiwowar** [comment]
Nie dostałam żadnego zaproszenia do grupy.

**Comment by mkrasinski** [comment]
@mpiwowar  Wyslalem jeszcze raz na -adres usuniety-
Jesli nie doszlo to moze sprobuje na adres gmailowy ?

**Comment by mpiwowar** [comment]
Prosze na gmail-owy przesłać.
MP

> Wyslalem jeszcze raz na mpiwowar@cm-uj.krakow.pl
> Jesli nie doszlo to moze sprobuje na adres gmailowy ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mkrasinski/CodonProb/issues/7#issuecomment-94482433

## 

dr Monika Piwowar
Uniwersytet Jagiellonski, Collegium Medicum, ZBiT
mpiwowar@cm-uj.krakow.pl
+48(12)422 77 64; tel. kom. 517197472

**Comment by mkrasinski** [comment]
@mpiwowar Wyslane !
